"""Aerodynamic action-effect model: how blade pitch and yaw change rotor loads.

Why this module exists
---------------------
FLOATBench holds the baseline turbine controller *fixed*: every one of its
19,404 OpenFAST runs follows the same IEC 61400-3-2 DLC 1.2 control schedule.
The dataset therefore contains no information about how the rotor responds to a
*different* pitch or yaw command - which is exactly what a load-relief RL agent
must learn. This module supplies that missing sensitivity from official
reference-turbine aerodynamic data.

Data sources (both official IEA-22-280-RWT, Apache-2.0)
-------------------------------------------------------
1. Rotor performance surfaces `Cp(theta, lambda)`, `Ct(theta, lambda)`,
   `Cq(theta, lambda)` on a 20 x 20 grid spanning pitch -5 deg .. 45 deg and
   tip-speed ratio 2 .. 14. Generated by the ROSCO toolbox from the actual
   blade geometry and airfoil polars. This is a *measured* aerodynamic surface,
   so the off-schedule pitch sensitivity is real rather than assumed.
2. The 22 OpenFAST steady-state operating points, which fix the absolute
   baseline thrust / power / Ct / Cp and the baseline pitch schedule.

Ratio anchoring
---------------
The performance surface and the steady-state points are two independent
artefacts and do not agree to machine precision (different solver settings,
tip-loss and drivetrain treatment). We therefore use the surface only for the
dimensionless *relative* effect of a control action,

    Ct(lambda, theta_base + dtheta) / Ct(lambda, theta_base)

and multiply that ratio onto the absolute steady-state baseline. Consequences:

* at zero control offset the pipeline reproduces the official steady-state
  thrust and power exactly, by construction;
* non-zero offsets perturb it using real tabulated aerodynamics.

Yaw uses the standard cosine-power laws, power ~ cos^1.88(gamma) and
thrust ~ cos^2(gamma); the thrust exponent is the momentum-consistent
normal-component scaling and the power exponent is a widely used empirical
value for rotor power under yaw misalignment.

See docs/LIMITATIONS.md for what this model does and does not capture (it is a
steady, rigid-rotor, quasi-static description - not an aeroelastic simulation).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

from .turbine import BaselineSchedule, TurbineProperties, load_turbine

# Yaw cosine-law exponents.
YAW_POWER_EXPONENT = 1.88
YAW_THRUST_EXPONENT = 2.0

# Guard against dividing by a vanishing baseline coefficient.
_RATIO_FLOOR = 1e-4
_MAX_RATIO = 3.0

# Number of tsr points used to tabulate the Cp-optimal pitch curve (see
# `PerformanceSurface.cp_optimal_pitch`). Must be dense enough that linear
# interpolation between grid points tracks the (nonlinear) true optimum to
# well under the smallest pitch offset the action space can command.
_N_TSR_OVERSAMPLE = 2001


@dataclass(frozen=True)
class PerformanceSurface:
    """Bilinear interpolant over the official Cp / Ct / Cq rotor performance grid."""

    pitch_deg: np.ndarray  # ascending, shape (n_pitch,)
    tsr: np.ndarray  # ascending, shape (n_tsr,)
    cp: np.ndarray  # shape (n_pitch, n_tsr)
    ct: np.ndarray
    cq: np.ndarray

    @classmethod
    def from_csv(cls, path: Path) -> "PerformanceSurface":
        frame = pd.read_csv(path)
        pitch = np.sort(frame["pitch_deg"].unique())
        tsr = np.sort(frame["tsr"].unique())
        shape = (pitch.size, tsr.size)
        pivot = {}
        for name in ("cp", "ct", "cq"):
            grid = (
                frame.pivot(index="pitch_deg", columns="tsr", values=name)
                .reindex(index=pitch, columns=tsr)
                .to_numpy(dtype=float)
            )
            if grid.shape != shape or np.isnan(grid).any():
                raise ValueError(f"rotor performance grid for {name} is incomplete")
            pivot[name] = grid
        return cls(pitch_deg=pitch, tsr=tsr, **pivot)

    def _interp(self, grid: np.ndarray, pitch_deg, tsr):
        """Bilinear interpolation with clamping at the grid edges."""
        pitch_deg = np.asarray(pitch_deg, dtype=float)
        tsr = np.asarray(tsr, dtype=float)
        pitch_deg, tsr = np.broadcast_arrays(pitch_deg, tsr)

        p = np.clip(pitch_deg, self.pitch_deg[0], self.pitch_deg[-1])
        t = np.clip(tsr, self.tsr[0], self.tsr[-1])

        i = np.clip(np.searchsorted(self.pitch_deg, p, side="right") - 1, 0, self.pitch_deg.size - 2)
        j = np.clip(np.searchsorted(self.tsr, t, side="right") - 1, 0, self.tsr.size - 2)

        p0, p1 = self.pitch_deg[i], self.pitch_deg[i + 1]
        t0, t1 = self.tsr[j], self.tsr[j + 1]
        wp = (p - p0) / (p1 - p0)
        wt = (t - t0) / (t1 - t0)

        v00 = grid[i, j]
        v10 = grid[i + 1, j]
        v01 = grid[i, j + 1]
        v11 = grid[i + 1, j + 1]
        return (
            v00 * (1 - wp) * (1 - wt)
            + v10 * wp * (1 - wt)
            + v01 * (1 - wp) * wt
            + v11 * wp * wt
        )

    def power_coefficient(self, pitch_deg, tsr):
        return self._interp(self.cp, pitch_deg, tsr)

    def thrust_coefficient(self, pitch_deg, tsr):
        return self._interp(self.ct, pitch_deg, tsr)

    def torque_coefficient(self, pitch_deg, tsr):
        return self._interp(self.cq, pitch_deg, tsr)

    def cp_optimal_pitch(self, tsr):
        """Blade pitch [deg] that maximises Cp at a given tip-speed ratio.

        Found by dense oversampling on *both* axes, then linearly interpolated
        over tsr. This is the reference angle used to correct the below-rated
        pitch mismatch between the steady-state schedule and the performance
        surface - see `_cp_optimal_pitch_grid` and the docstring of
        `RotorAero._ratios`.

        Oversampling only the pitch axis while keeping the native 20-point tsr
        axis is not fine enough: the optimal pitch does not vary linearly
        across tsr, so linearly interpolating between only 20 (tsr, optimum)
        pairs can under-shoot the true optimum by more than half a degree
        between grid columns (empirically up to 0.55 deg here). That residual
        reopens a smaller version of the free-feathering artefact for query
        points that fall between native tsr columns. Oversampling the tsr axis
        too (`_N_TSR_OVERSAMPLE` points) reduces that residual to <0.01 deg.
        """
        return np.interp(
            np.asarray(tsr, dtype=float), self._tsr_fine, self._cp_optimal_pitch_grid
        )

    def __post_init__(self) -> None:
        fine_pitch = np.linspace(self.pitch_deg[0], self.pitch_deg[-1], 4001)
        tsr_fine = np.linspace(self.tsr[0], self.tsr[-1], _N_TSR_OVERSAMPLE)
        optimal = np.empty(tsr_fine.size, dtype=float)
        for index, tsr_value in enumerate(tsr_fine):
            cp_curve = self._interp(self.cp, fine_pitch, np.full_like(fine_pitch, tsr_value))
            optimal[index] = fine_pitch[int(np.argmax(cp_curve))]
        object.__setattr__(self, "_tsr_fine", tsr_fine)
        object.__setattr__(self, "_cp_optimal_pitch_grid", optimal)


class RotorAero:
    """Quasi-static rotor response to collective pitch and yaw, ratio-anchored."""

    def __init__(
        self,
        properties: TurbineProperties,
        schedule: BaselineSchedule,
        surface: PerformanceSurface,
    ):
        self.properties = properties
        self.schedule = schedule
        self.surface = surface

    # ------------------------------------------------------------------
    def _ratios(self, wind_speed, pitch_offset_deg):
        """Relative Ct / Cp change caused by a collective pitch offset.

        Below rated, the reference steady-state schedule (which includes peak
        shaving) sits *below* the performance surface's own Cp-optimal pitch at
        the same tip-speed ratio - the two official artefacts were produced by
        different solver configurations and disagree along the pitch axis, not
        just in overall level. Ratio-anchoring on the raw schedule pitch would
        then let a positive (feathering) offset move *towards* the surface's
        optimum, so Ct/Cp momentarily rise before falling - i.e. a "free" load
        reduction, which is not physical for a tuned controller under any
        aerodynamic model.

        The fix is to anchor the ratio on the *effective* reference pitch

            pitch_ref = max(pitch_base, cp_optimal_pitch(tsr))

        instead of the raw schedule pitch. This is equivalent to defining the
        commanded action as an offset from whichever is more feathered: the
        real controller's schedule, or the surface's own optimum. Because
        `cp_optimal_pitch <= pitch_base` above rated (verified over the full
        22-point schedule), `pitch_ref == pitch_base` there and behaviour is
        unchanged; below rated the correction removes the free-power region
        entirely, so Ct and Cp are then monotonically non-increasing in the
        offset by construction and no post-hoc clamping is needed.

        Absolute thrust and power still come from the schedule at
        `pitch_offset_deg = 0` (ratio = 1 there by definition), so the
        zero-action exactness of the pipeline is unaffected.
        """
        tsr = self.schedule.tip_speed_ratio(wind_speed)
        pitch_base = self.schedule.pitch_deg(wind_speed)
        pitch_offset_deg = np.asarray(pitch_offset_deg, dtype=float)

        pitch_ref = np.maximum(pitch_base, self.surface.cp_optimal_pitch(tsr))
        pitch_act = pitch_ref + pitch_offset_deg

        ct_ref = self.surface.thrust_coefficient(pitch_ref, tsr)
        cp_ref = self.surface.power_coefficient(pitch_ref, tsr)
        ct_act = self.surface.thrust_coefficient(pitch_act, tsr)
        cp_act = self.surface.power_coefficient(pitch_act, tsr)

        # Negative tabulated Cp means the rotor is no longer producing torque.
        ct_ratio = np.clip(ct_act / np.maximum(ct_ref, _RATIO_FLOOR), 0.0, _MAX_RATIO)
        cp_ratio = np.clip(
            np.maximum(cp_act, 0.0) / np.maximum(cp_ref, _RATIO_FLOOR), 0.0, _MAX_RATIO
        )

        # Numerical safety net only: pitch_ref already guarantees monotonicity
        # analytically (see docstring), but bilinear interpolation error near
        # the grid boundary could in principle produce a ratio infinitesimally
        # above 1. Clamp defensively; this should bind at machine precision at
        # most, never trade off a physical amount of power or thrust.
        feathering = pitch_offset_deg >= 0.0
        cp_ratio = np.where(feathering, np.minimum(cp_ratio, 1.0), cp_ratio)
        ct_ratio = np.where(feathering, np.minimum(ct_ratio, 1.0), ct_ratio)
        return ct_ratio, cp_ratio, tsr, pitch_base

    def response(self, wind_speed, pitch_offset_deg=0.0, yaw_error_deg=0.0) -> dict:
        """Rotor response under a control action, anchored on official steady states.

        Parameters
        ----------
        wind_speed : array-like
            Mean hub-height wind speed [m/s].
        pitch_offset_deg : array-like
            Collective blade-pitch offset added to the baseline schedule [deg].
            Positive = towards feather = load shedding.
        yaw_error_deg : array-like
            Net rotor-inflow yaw misalignment [deg] remaining after the yaw action.

        Returns
        -------
        dict
            thrust_n, electrical_power_w, ct, cp, the dimensionless ratios
            relative to the uncontrolled baseline, and the baseline values.
        """
        wind_speed = np.asarray(wind_speed, dtype=float)
        ct_ratio, cp_ratio, tsr, pitch_base = self._ratios(wind_speed, pitch_offset_deg)

        cos_gamma = np.cos(np.radians(np.clip(np.abs(np.asarray(yaw_error_deg, dtype=float)), 0.0, 89.0)))
        yaw_thrust_factor = cos_gamma**YAW_THRUST_EXPONENT
        yaw_power_factor = cos_gamma**YAW_POWER_EXPONENT

        total_ct_ratio = ct_ratio * yaw_thrust_factor
        total_cp_ratio = cp_ratio * yaw_power_factor

        thrust_base = self.schedule.thrust_n(wind_speed)
        power_base = self.schedule.electrical_power_w(wind_speed)

        power = np.clip(power_base * total_cp_ratio, 0.0, self.properties.rated_power_w)

        return {
            "thrust_n": thrust_base * total_ct_ratio,
            "electrical_power_w": power,
            "ct": self.schedule.ct(wind_speed) * total_ct_ratio,
            "cp": self.schedule.cp(wind_speed) * total_cp_ratio,
            "ct_ratio": total_ct_ratio,
            "cp_ratio": total_cp_ratio,
            "tip_speed_ratio": tsr,
            "pitch_total_deg": pitch_base + np.asarray(pitch_offset_deg, dtype=float),
            "thrust_base_n": thrust_base,
            "power_base_w": power_base,
        }

    def thrust_sensitivity_to_wind(self, wind_speed, pitch_offset_deg=0.0, yaw_error_deg=0.0):
        """dT/dV [N per m/s] at a fixed control setting.

        With T = 0.5 rho A Ct V^2 and Ct locally insensitive to V at fixed
        (lambda, theta), dT/dV = rho A Ct V. This converts turbulent wind-speed
        fluctuations into thrust fluctuations, and hence into the aerodynamic
        share of tower fore-aft fatigue loading (see fowt_rl.load_model).
        """
        wind_speed = np.asarray(wind_speed, dtype=float)
        response = self.response(wind_speed, pitch_offset_deg, yaw_error_deg)
        gradient = (
            self.properties.air_density_kgm3
            * self.properties.rotor_area_m2
            * response["ct"]
            * wind_speed
        )
        return gradient, response

    # ------------------------------------------------------------------
    def cross_validate(self) -> dict:
        """Cross-check the two official artefacts against each other.

        Compares Ct and Cp read off the rotor performance surface at the
        baseline (pitch, TSR) operating points against the values derived from
        the steady-state runs. Agreement is *not* required by the pipeline
        (ratio anchoring removes any bias), but it is a useful indicator of how
        consistent the surface is with the operating schedule.
        """
        table = self.schedule.table
        tsr = table["tip_speed_ratio"].to_numpy(dtype=float)
        pitch = table["pitch"].to_numpy(dtype=float)
        ct_ref = table["ct_base"].to_numpy(dtype=float)
        cp_ref = table["cp_base"].to_numpy(dtype=float)

        ct_surf = self.surface.thrust_coefficient(pitch, tsr)
        cp_surf = self.surface.power_coefficient(pitch, tsr)

        def rel_err(a, b):
            return float(np.mean(np.abs(a - b) / np.maximum(np.abs(b), 1e-6)))

        return {
            "n_operating_points": int(len(tsr)),
            "ct_mean_abs_rel_error": rel_err(ct_surf, ct_ref),
            "cp_mean_abs_rel_error": rel_err(cp_surf, cp_ref),
            "ct_pearson_r": float(np.corrcoef(ct_surf, ct_ref)[0, 1]),
            "cp_pearson_r": float(np.corrcoef(cp_surf, cp_ref)[0, 1]),
        }

    def pitch_sensitivity_report(self, wind_speeds=(6.0, 9.0, 11.0, 14.0, 18.0, 22.0)) -> dict:
        """Report dP/dtheta and dT/dtheta at +1 deg for a few wind speeds.

        Useful as a physical plausibility check: for multi-MW machines above
        rated, dP/dtheta is expected to be of order -1 MW/deg.
        """
        out = {}
        for v in wind_speeds:
            base = self.response(v, 0.0, 0.0)
            pert = self.response(v, 1.0, 0.0)
            out[f"V={v:g}"] = {
                "dP_dpitch_MW_per_deg": float(
                    (pert["electrical_power_w"] - base["electrical_power_w"]) / 1e6
                ),
                "dT_dpitch_kN_per_deg": float((pert["thrust_n"] - base["thrust_n"]) / 1e3),
                "ct_base": float(base["ct"]),
            }
        return out


def _turbine_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "data" / "turbine"


def _calibration_path() -> Path:
    return Path(__file__).resolve().parents[2] / "data" / "calibration" / "aero_reference_check.json"


@lru_cache(maxsize=2)
def load_aero(write_report: bool = True) -> RotorAero:
    """Build the rotor aerodynamic model from official reference data."""
    properties, schedule = load_turbine()
    perf_path = _turbine_dir() / "iea22_rotor_performance.csv"
    if not perf_path.exists():
        raise FileNotFoundError(
            f"{perf_path} not found. Run: python scripts/fetch_turbine_data.py"
        )
    model = RotorAero(properties, schedule, PerformanceSurface.from_csv(perf_path))

    if write_report:
        report = {
            "surface_vs_steady_state": model.cross_validate(),
            "pitch_sensitivity": model.pitch_sensitivity_report(),
            "yaw_power_exponent": YAW_POWER_EXPONENT,
            "yaw_thrust_exponent": YAW_THRUST_EXPONENT,
            "note": (
                "Absolute values come from the OpenFAST steady states; the "
                "performance surface supplies only relative control sensitivity "
                "(ratio anchoring), so the errors reported here do not bias the "
                "generated dataset."
            ),
        }
        path = _calibration_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return model
