"""Extract the IEA-22-280-RWT reference aerodynamic data used by the pipeline.

Source (official, Apache-2.0):
    https://github.com/IEAWindSystems/IEA-22-280-RWT
      windIO/IEA-22-280-RWT.yaml                          -> global properties
      outputs/01_steady_states/OpenFAST/
        iea-22-280-rwt-steady-states-of.yaml              -> baseline operating points
      OpenFAST/IEA-22-280-RWT/
        IEA-22-280-RWT_Cp_Ct_Cq.txt                       -> rotor performance surfaces

Three artefacts are produced:

1. `iea22_steady_states.csv` - the 22 baseline OpenFAST operating points.
   The steady-state YAML contains large `distributed` blade arrays we do not
   need, so we stream it and keep only the `configuration` and `integrated`
   mappings.  From these we derive the *real* baseline coefficients

       Ct_base(V) = T / (0.5 rho A V^2)
       Cp_base(V) = P_mech / (0.5 rho A V^3)

2. `iea22_rotor_performance.csv` - the official 20 x 20 rotor performance
   surfaces Cp, Ct, Cq tabulated over (blade pitch, tip-speed ratio).  These
   are generated by the ROSCO toolbox from the actual blade geometry and
   airfoil polars, and are what give the pipeline a *measured* off-schedule
   pitch sensitivity instead of a fitted one.

3. `iea22_properties.json` - scalar assembly / control properties.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/IEAWindSystems/IEA-22-280-RWT/main"
STEADY_URL = f"{RAW}/outputs/01_steady_states/OpenFAST/iea-22-280-rwt-steady-states-of.yaml"
WINDIO_URL = f"{RAW}/windIO/IEA-22-280-RWT.yaml"
PERF_URL = f"{RAW}/OpenFAST/IEA-22-280-RWT/IEA-22-280-RWT_Cp_Ct_Cq.txt"

# Air density used by the reference OpenFAST model (AeroDyn AirDens).
RHO_AIR = 1.225

_CONFIG_RE = re.compile(r"^\s*-\s*configuration:\s*(\{.*\})\s*$")
_INTEGRATED_RE = re.compile(r"^\s*integrated:\s*(\{.*\})\s*$")


def _flow_map(text: str) -> dict:
    """Parse a YAML flow mapping `{a: 1.0, b: 2.0}` without a YAML dependency."""
    body = text.strip().lstrip("{").rstrip("}")
    out: dict[str, float] = {}
    for item in body.split(","):
        if not item.strip():
            continue
        key, _, value = item.partition(":")
        out[key.strip()] = float(ast.literal_eval(value.strip()))
    return out


def fetch(url: str, dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and dest.stat().st_size > 0:
        print(f"[cache] {dest}")
        return dest
    print(f"[get]   {url}")
    with urllib.request.urlopen(url, timeout=120) as response:
        dest.write_bytes(response.read())
    return dest


def parse_steady_states(path: Path) -> list[dict]:
    """Stream the steady-state YAML, pairing each configuration with its integrated outputs."""
    cases: list[dict] = []
    pending: dict | None = None
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            config_match = _CONFIG_RE.match(line)
            if config_match:
                if pending is not None:
                    cases.append(pending)
                pending = _flow_map(config_match.group(1))
                continue
            integrated_match = _INTEGRATED_RE.match(line)
            if integrated_match and pending is not None:
                pending.update(_flow_map(integrated_match.group(1)))
    if pending is not None:
        cases.append(pending)
    return cases


def _numbers(line: str) -> list[float]:
    return [float(token) for token in line.replace(",", " ").split()]


def parse_rotor_performance(path: Path) -> dict:
    """Parse the ROSCO-format Cp/Ct/Cq rotor performance file.

    Layout (ROSCO toolbox convention):
        # Pitch angle vector ...      -> next non-comment line: pitch axis [deg]
        # TSR vector ...              -> next non-comment line: TSR axis [-]
        # Power coefficient           -> n_tsr rows x n_pitch columns
        # Thrust coefficient          -> n_tsr rows x n_pitch columns
        # Torque coefficient          -> n_tsr rows x n_pitch columns
    """
    lines = path.read_text(encoding="utf-8").splitlines()

    def next_values(start: int) -> tuple[list[float], int]:
        for index in range(start, len(lines)):
            stripped = lines[index].strip()
            if not stripped or stripped.startswith("#"):
                continue
            return _numbers(stripped), index + 1
        raise ValueError("unexpected end of rotor performance file")

    pitch: list[float] | None = None
    tsr: list[float] | None = None
    matrices: dict[str, list[list[float]]] = {}

    index = 0
    while index < len(lines):
        stripped = lines[index].strip()
        lowered = stripped.lower()
        if stripped.startswith("#") and "pitch angle vector" in lowered:
            pitch, index = next_values(index + 1)
            continue
        if stripped.startswith("#") and "tsr vector" in lowered:
            tsr, index = next_values(index + 1)
            continue
        matrix_key = None
        if stripped.startswith("#") and "power coefficient" in lowered:
            matrix_key = "cp"
        elif stripped.startswith("#") and "thrust coefficient" in lowered:
            matrix_key = "ct"
        elif stripped.startswith("#") and "torque coefficient" in lowered:
            matrix_key = "cq"
        if matrix_key is not None:
            if pitch is None or tsr is None:
                raise ValueError("axes must appear before coefficient matrices")
            rows: list[list[float]] = []
            cursor = index + 1
            while cursor < len(lines) and len(rows) < len(tsr):
                candidate = lines[cursor].strip()
                cursor += 1
                if not candidate or candidate.startswith("#"):
                    continue
                values = _numbers(candidate)
                if len(values) != len(pitch):
                    raise ValueError(
                        f"{matrix_key}: expected {len(pitch)} columns, got {len(values)}"
                    )
                rows.append(values)
            if len(rows) != len(tsr):
                raise ValueError(f"{matrix_key}: expected {len(tsr)} rows, got {len(rows)}")
            matrices[matrix_key] = rows
            index = cursor
            continue
        index += 1

    missing = {"cp", "ct", "cq"} - set(matrices)
    if missing or pitch is None or tsr is None:
        raise ValueError(f"rotor performance file incomplete (missing {sorted(missing)})")

    return {"pitch_deg": pitch, "tsr": tsr, **matrices}


def write_rotor_performance(perf: dict, out_path: Path) -> int:
    """Write the performance surfaces as a tidy long-format CSV."""
    header = "pitch_deg,tsr,cp,ct,cq"
    rows = [header]
    for i, tsr in enumerate(perf["tsr"]):
        for j, pitch in enumerate(perf["pitch_deg"]):
            rows.append(
                f"{pitch:.6g},{tsr:.6g},"
                f"{perf['cp'][i][j]:.8g},{perf['ct'][i][j]:.8g},{perf['cq'][i][j]:.8g}"
            )
    out_path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return len(rows) - 1


def parse_properties(path: Path) -> dict:
    """Pull the handful of scalar assembly/control properties we need."""
    wanted = {
        "hub_height": "hub_height_m",
        "rotor_diameter": "rotor_diameter_m",
        "cut_in_wind_speed": "cut_in_wind_speed_ms",
        "cut_out_wind_speed": "cut_out_wind_speed_ms",
        "rated_rotor_speed": "rated_rotor_speed_rpm",
        "optimal_tsr": "optimal_tsr",
    }
    found: dict[str, float] = {}
    text = path.read_text(encoding="utf-8")
    for key, alias in wanted.items():
        match = re.search(rf"^\s*{key}:\s*([0-9.eE+-]+)\s*$", text, re.MULTILINE)
        if match:
            found[alias] = float(match.group(1))
    # rated_power appears twice (assembly + control); both are 22 MW.
    match = re.search(r"^\s*rated_power:\s*([0-9.eE+-]+)\s*$", text, re.MULTILINE)
    if match:
        found["rated_power_w"] = float(match.group(1))
    return found


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="data/turbine", type=Path)
    parser.add_argument("--cache-dir", default="data/raw/turbine_src", type=Path)
    args = parser.parse_args()

    steady_path = fetch(STEADY_URL, args.cache_dir / "iea-22-280-rwt-steady-states-of.yaml")
    windio_path = fetch(WINDIO_URL, args.cache_dir / "IEA-22-280-RWT.yaml")
    perf_path = fetch(PERF_URL, args.cache_dir / "IEA-22-280-RWT_Cp_Ct_Cq.txt")

    cases = parse_steady_states(steady_path)
    if not cases:
        raise SystemExit("no steady-state cases parsed - upstream format may have changed")
    props = parse_properties(windio_path)
    props["air_density_kgm3"] = RHO_AIR
    radius = props["rotor_diameter_m"] / 2.0
    area = 3.141592653589793 * radius**2
    props["rotor_area_m2"] = area
    props["source"] = "IEAWindSystems/IEA-22-280-RWT (Apache-2.0)"
    props["steady_state_source"] = STEADY_URL
    props["properties_source"] = WINDIO_URL
    props["rotor_performance_source"] = PERF_URL

    args.out_dir.mkdir(parents=True, exist_ok=True)

    perf = parse_rotor_performance(perf_path)
    perf_csv = args.out_dir / "iea22_rotor_performance.csv"
    n_perf = write_rotor_performance(perf, perf_csv)
    props["rotor_performance_grid"] = {
        "n_pitch": len(perf["pitch_deg"]),
        "n_tsr": len(perf["tsr"]),
        "pitch_deg_range": [min(perf["pitch_deg"]), max(perf["pitch_deg"])],
        "tsr_range": [min(perf["tsr"]), max(perf["tsr"])],
    }

    header = [
        "wind_speed",
        "rotor_speed",
        "pitch",
        "tip_speed_ratio",
        "mechanical_power",
        "electrical_power",
        "generator_torque",
        "rotor_thrust",
        "rotor_torque",
        "ct_base",
        "cp_base",
    ]
    lines = [",".join(header)]
    for case in sorted(cases, key=lambda c: c["wind_speed"]):
        v = case["wind_speed"]
        thrust = case["rotor_thrust"]
        power = case["mechanical_power"]
        case["ct_base"] = thrust / (0.5 * RHO_AIR * area * v**2)
        case["cp_base"] = power / (0.5 * RHO_AIR * area * v**3)
        lines.append(",".join(f"{case[col]:.10g}" for col in header))

    csv_path = args.out_dir / "iea22_steady_states.csv"
    csv_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    json_path = args.out_dir / "iea22_properties.json"
    json_path.write_text(json.dumps(props, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"[write] {csv_path}  ({len(cases)} operating points)")
    print(f"[write] {perf_csv}  ({n_perf} grid points)")
    print(f"[write] {json_path}")
    print(
        "        V range {:.1f}-{:.1f} m/s | Ct {:.3f}-{:.3f} | Cp max {:.3f}".format(
            min(c["wind_speed"] for c in cases),
            max(c["wind_speed"] for c in cases),
            min(c["ct_base"] for c in cases),
            max(c["ct_base"] for c in cases),
            max(c["cp_base"] for c in cases),
        )
    )


if __name__ == "__main__":
    main()
